Start testing model 4 (z,f,s)
Traceback (most recent call last):
  File "test_models.py", line 133, in <module>
    run_tests(results_save_path, test_set_paths)
  File "test_models.py", line 46, in run_tests
    trained_model = torch.load(model_save_path)
  File "/mnt/home/f0102398/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/mnt/home/f0102398/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/mnt/home/f0102398/anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/OpenChem/model_4_zfs.pkl'
Start testing model 4 (z,f,s)
Start testing model 4 (z,f,s)
Start testing model 4 (z,f,s)
Start testing model 4 (z,f,s)
